# Generated by Django 2.2.12 on 2021-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, verbose_name='账户')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
            ],
        ),
    ]
