# Generated by Django 2.2.12 on 2021-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='病人姓名')),
                ('gender', models.CharField(blank=True, max_length=5, null=True, verbose_name='病人性别')),
                ('age', models.CharField(blank=True, max_length=5, null=True, verbose_name='病人年龄')),
                ('position', models.CharField(max_length=20, verbose_name='影像部位')),
                ('url', models.URLField()),
            ],
        ),
    ]
