# Generated by Django 2.2.12 on 2021-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='病人年龄'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='病人姓名'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
